### ISSUE TITLE
Could not enable logging by `Prusti.toml`

### ISSUE THREAD

**Issue by hiroki-chen** [viperproject/prusti-dev#1218]
The developer guide of Prusti says that we can provide `cargo-prusti` with a configuration manifest file as a substitute for command line arguments. So I placed `Prusti.toml` under the root directory of my project, and every configuration key took effect except those for logging, like `LOG`, `LOG_DIR`, and `LOG_STYLE`.

My `Prusti.toml` wrote

```toml
check_overflows = true
check_panics = true
no_verify_deps = true
print_desugared_specs = true
print_typeckd_specs = true
hide_uuids = true
assert_timeout = 10000
# ----
# None of the following works.
log = "info"
log_dir = "target/verify"
log_style = "auto"
# ----
optimizations = "inline_constant_functions,delete_unused_predicates,optimize_folding,remove_empty_if,purify_vars,remove_unused_vars,remove_trivial_assertions,clean_cfg"
```

The logging was enabled when I set the environment variable `PRUSTI_LOG` to `info`.

```shelll
$ PRUSTI_LOG=info ~/prusti-dev/target/release/cargo-prusti
```

However, the following command didn't enable logging:

```shell
$ ~/prusti-dev/target/release/cargo-prusti
```

I wonder if there is something that accidentally shadows the value from the configuration file, or is it related to `env_logger` issues?

BTW, I'm using the latest version of Prusti.
