### ISSUE TITLE
Backward-incompatible `prusti_contracts`

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-dev#1446]
Because of the [versioning issue reported last week](https://prusti.zulipchat.com/#narrow/stream/236614-general/topic/VSCode.20error.3A.20Prusti.20version.200.2E2.2E1/near/383987332), it's now no longer possible to verify, using an old Prusti release, crates that make use of `prusti_contracts`. Even specifying the following doesn't work; the error is always "[E0635] unknown feature `extract_if`."
```toml
[dependencies]
prusti-contracts = "=0.1.4"
prusti-contracts-proc-macros = "=0.1.4"
```

The error is`[E0635] unknown feature 'extract_if'`, reported on `.cargo/registry/src/github.../prusti-specs-0.1.10/src/lib.rs`.
