### ISSUE TITLE
Update rust nightly to support codegen-backend

### ISSUE THREAD

**Issue by sigmaSd** [viperproject/prusti-dev#1478]
I'm using 
```toml
[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"
```
so it would be great if I don't have to remove it to run prusti
